### ISSUE TITLE
проблеми з відображенням шрифтів у системному треї

### ISSUE THREAD

**Issue by ghost** [Z-beam/MovaFlag#2]
# опис проблеми
при правому кліку на іконку програми в треї, шрифт відображаєтья не коректно

## скріншот
![image](https://github.com/user-attachments/assets/b1f96006-fd7e-4140-bb47-07881f580efc)

## ос
OS Version:                10.0.22631 N/A Build 22631
OS Build Type:             Multiprocessor Free
мова інтерфейсу:       англійська

**Comment by antiqrom** [comment]
В мене ось так) мова англійська, стоїть прапорець біля розширеної підтримки utf8
![6aVXpMsdIa](https://github.com/user-attachments/assets/a9699ba3-46ff-4eb0-a4a0-2ee4e871cbbe)

**Comment by Z-beam** [comment]
Зовсім скоро буде оновлення, де цю проблему буде вирішено.
