### ISSUE TITLE
Баг - відображення мови у непортрібних мічцях

### ISSUE THREAD

**Issue by kybarg** [Z-beam/MovaFlag#7]
Часто на вебсайстайх прапорець показується не тільки при наведенні на поля вводу але також при наведенні на звичайний тест.
Не знаю наскільки це можливо з windows api але булоб краще аби в місцях де ввід неможливий, а лише виділення тесту, відіображати звичайний курсор без прапорця.

**Comment by Z-beam** [comment]
Це не баг, це звичайний режим роботи програми. Робив її для себе та просто поділився зі спільнотою. Покращувати/розширювати функціонал не планую.

**Comment by kybarg** [comment]
Дуже шкода, мені дуже сподобалась ця ідея
